<?php 
  
 $config=array (
  'ajax_topic_time' => '45',
  'api_enable' => 1,
  'attach_enable' => 1,
  'attach_files_limit' => 5,
  'attach_size_limit' => 5120,
  'auth_key' => 'JG2hw6uv07TA0PE0AwvUoqWA6RQFLY1p',
  'cache_table_num' => 16,
  'charset' => 'utf-8',
  'city_status' => '1',
  'close_second_verify_enable' => '0',
  'cookie_expire' => '30',
  'cookie_path' => '/',
  'cookie_prefix' => 'yqweibo_Tzd1JU_',
  'copyright' => '',
  'count_online_user' => '1',
  'credits_filed' => 'extcredits3',
  'db_host' => 'localhost',
  'db_name' => 'weibo',
  'db_pass' => 'root',
  'db_port' => '3306',
  'db_table_prefix' => 'weibo_',
  'db_type' => 'mysql',
  'db_user' => 'root',
  'default_module' => 'topic',
  'event_open' => '1',
  'extcredits_enable' => 1,
  'extra_domain' => '',
  'extra_domains' => 
  array (
  ),
  'face_verify' => '0',
  'follow_limit' => 2000,
  'gzip' => 0,
  'icp' => '备案申请中',
  'image_uploadify_queue_size_limit' => '3',
  'install_lock_time' => 1343384299,
  'invite_by_admin' => '1',
  'invite_count_max' => '30',
  'invite_enable' => '5',
  'invite_limit' => '5',
  'is_report' => '0',
  'is_signature' => '1',
  'is_topic_user_follow' => '1',
  'jishigou_founder' => '1',
  'lastpost_time' => '5',
  'level_radio' => '1',
  'login_enable' => 1,
  'maxthumbheight' => '6000',
  'maxthumbwidth' => '800',
  'mobile_url' => 'http://localhost/yqweibo/mobile',
  'no_verify_email_role_id' => '5',
  'normal_default_role_id' => '3',
  'notice_to_admin' => '',
  'only_show_vip_topic' => '0',
  'qmd_file_url' => './images/qmd/',
  'qqwb_enable' => 1,
  'qun_attach_enable' => 1,
  'qun_setting' => 
  array (
    'qun_open' => '1',
    'new_qun' => '1',
    'tc_qun' => '1',
    'img_size' => 200,
    'member_num' => 300,
    'admin_num' => 5,
    'qun_ploy' => 
    array (
      'avatar' => '1',
      'vip' => '1',
    ),
  ),
  'refresh_times_banned_ip' => '10',
  'refresh_times_banned_ip_time' => '86400',
  'regclosemessage' => '',
  'register_invite_input' => '1',
  'regstatus' => 
  array (
    0 => 'normal',
    1 => 'invite',
  ),
  'robot_enable' => 1,
  'safe_key' => 'rEt1GT5ZMEKcfBUC5IoGGFwc1oHXTOHs',
  'sign' => 
  array (
    'sign_enable' => '1',
  ),
  'sign_verify' => '0',
  'sina_enable' => 1,
  'site_admin_email' => 'mg90@foxmail.com',
  'site_admin_nickname' => '管理员',
  'site_closed' => '0',
  'site_domain' => 'localhost',
  'site_name' => '舆情微博',
  'site_notice' => NULL,
  'site_url' => 'http://localhost/yqweibo',
  'slide_enable' => 0,
  'slide_index_enable' => 1,
  'style_three_tol' => 1,
  'template_path' => 'default',
  'template_root_path' => './templates/',
  'theme_bg_color' => '#73CFF1',
  'theme_bg_image_type' => 'center',
  'theme_id' => 't2',
  'theme_link_color' => '#2E75BC',
  'theme_text_color' => '#333333',
  'third_party_regstatus' => 
  array (
    0 => 'sina',
    1 => 'qqwb',
  ),
  'thumbheight' => 120,
  'thumbwidth' => 120,
  'timezone' => '8',
  'today_topic' => '',
  'tongji' => '',
  'topic_cut_length' => 140,
  'topic_input_length' => 1000,
  'topic_length' => 140,
  'topic_level_radio' => '1',
  'topic_modify_time' => '60',
  'topic_myhome_time_limit' => '30',
  'topic_vip' => '0',
  'total_page_default' => '50',
  'upgrade_to_lock_version' => 35,
  'verify' => '0',
  'verify_alert' => '1',
  'video_status' => '1',
  'vote_open' => '1',
  'wap' => '1',
  'wap_url' => 'http://localhost/yqweibo/wap',
  'watermark_contents' => '1',
  'watermark_contents_color' => '#ffffff',
  'watermark_contents_size' => '12',
  'watermark_enable' => '0',
  'watermark_position' => 4,
  'widget_enable' => '0',
); 
 ?>
